# Example PlatformIO Project Configuration Override
# ------------------------------------------------------------------------------
# Copy to platformio_override.ini to activate overrides
# ------------------------------------------------------------------------------
# Please visit documentation: https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:esp32dev]
extends = env:esp32dev_V4_dio80
custom_usermods = four_line_display_ALT, rotary_encoder_ui_ALT
upload_port = COM6

build_flags =
    ${env:esp32dev_V4_dio80.build_flags}
    -Wno-shadow=compatible-local
    -D FLD_TYPE=SSD1351_128X128
    -D FLD_PIN_CS=21      ; ← change to your actual CS pin
    -D FLD_PIN_DC=19      ; ← change to your actual DC pin
    -D FLD_PIN_RESET=27   ; ← change to your actual RST pin (or -1)
    -D LEDPIN=33
    -D DEFAULT_LED_COUNT=130
    -D DEFAULT_LED_COLOR_ORDER=COL_ORDER_GRB
    -D ENCODER_CLK_PIN=22
    -D ENCODER_DT_PIN=34
    -D ENCODER_SW_PIN=15
    -D CLIENT_SSID='"NOVA_5030"'
    -D CLIENT_PASS='"give5469"'
